language: python
python:
    - "2.7"
install: "pip install -r requirements.txt"
script: pytest
notifications:
  email:
    recipients:
      - jeffstein@gmail.com
      - jstein@mitre.org
    on_success: never # default: change
    on_failure: always # default: always